### PR TITLE
Added visualize command to the readme

### PR DESCRIPTION
**Pull request by Skullbock**

### CODE REVIEW

**Comment by sebdesign** [comment]
Thanks a lot!

**Comment by Skullbock** [comment]
Thanks to you for this super helpful package. Using it a lot in my clients projects.
Just wanted that this thing would also be done:

https://github.com/efrontsa/nova-workflow/issues/7

:)

**Comment by sebdesign** [comment]
That would be awesome! But I've never used Nova before.

Is there a way to create packages for Nova without purchasing a license though?

**Comment by Skullbock** [comment]
I actually don't know. I have licenses for it for some clients projects so i never investigated. I guess you could ask taylor or david for one? Just for dev

**Comment by Skullbock** [comment]
If you want we can fork that package and make it support nova, like spatie does for their backup solution

**Comment by sebdesign** [comment]
I think I'll use Spatie's skeleton for Nova (https://github.com/spatie/skeleton-nova-tool) and try to implement that package's functionality.

Since you have a licence you could help me actually test the results. :)

**Comment by Skullbock** [comment]
That would be super cool! I would also help by adding features i found to be extremely helpful and have added in some of my projects.

Thanks!

**Comment by divan-mt** [comment]
> I think I'll use Spatie's skeleton for Nova ([spatie/skeleton-nova-tool](https://github.com/spatie/skeleton-nova-tool)) and try to implement that package's functionality.
> 
> Since you have a licence you could help me actually test the results. :)

I am actively using Laravel Nova and very must interested to test and give you feedback. Thank you.

**Pull request merged**
